export enum RoleName {
  INDIVIDUAL = 'INDIVIDUAL',
  BUSINESS = 'BUSINESS',
  MERCHANT = 'MERCHANT',
  CRYPTO_TRADER = 'CRYPTO_TRADER',
  GIFT_CARD_TRADER = 'GIFT_CARD_TRADER',
  DIASPORA_USER = 'DIASPORA_USER',
  SUPPORT_AGENT = 'SUPPORT_AGENT',
  COMPLIANCE_OFFICER = 'COMPLIANCE_OFFICER',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}
